# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.ssh.insert_key = false
  config.vm.box = "bento/centos-7.1"
  config.vm.hostname = "gihyo-devops-ansible.dev"
  config.vm.network "private_network", ip: "192.168.34.21"
end
